// AeroGuard — modelos 3D procedurales (Three.js r128)
window.AG=window.AG||{};
AG.createDrone=function(opts){const version=opts.version||'eco';const g=new THREE.Group();const hotspots=[];
const matBody=new THREE.MeshStandardMaterial({color:version==='pro'?0x2a3550:0x274156,roughness:.55,metalness:.35});
const matDark=new THREE.MeshStandardMaterial({color:0x141c2c,roughness:.7,metalness:.2});
const matArm=new THREE.MeshStandardMaterial({color:0x2b3a58,roughness:.5,metalness:.5});
const matProp=new THREE.MeshStandardMaterial({color:0xcfe0ff,roughness:.4,metalness:.1,transparent:true,opacity:.85});
const matAcc=new THREE.MeshStandardMaterial({color:version==='pro'?0xa06bff:0x2ee6a8,roughness:.4,metalness:.4});
const lower=new THREE.Mesh(new THREE.BoxGeometry(1.5,.12,1.1),matDark);lower.position.y=-.12;g.add(lower);
const upper=new THREE.Mesh(new THREE.BoxGeometry(1.4,.3,.95),matBody);g.add(upper);
const top=new THREE.Mesh(new THREE.BoxGeometry(1.1,.08,.7),matAcc);top.position.y=.2;g.add(top);
const stripe=new THREE.Mesh(new THREE.BoxGeometry(.1,.32,.97),new THREE.MeshStandardMaterial({color:version==='pro'?0xa06bff:0x2ee6a8,emissive:version==='pro'?0x5a2d99:0x0f6b4d,emissiveIntensity:.6}));stripe.position.set(.68,0,0);g.add(stripe);
[[-.55,-.4],[.55,-.4],[-.55,.4],[.55,.4]].forEach(p=>{const leg=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,.5),matDark);leg.position.set(p[0],-.45,p[1]);g.add(leg);});
[[1,1],[1,-1],[-1,-1],[-1,1]].forEach((a,i)=>{const ang=Math.atan2(a[1],a[0]);const len=1.15;const arm=new THREE.Mesh(new THREE.BoxGeometry(len,.07,.09),matArm);arm.position.set(Math.cos(ang)*len/2,0,Math.sin(ang)*len/2);arm.rotation.y=-ang;g.add(arm);const mx=Math.cos(ang)*len,mz=Math.sin(ang)*len;const motor=new THREE.Mesh(new THREE.CylinderGeometry(.11,.13,.2,16),matDark);motor.position.set(mx,.12,mz);g.add(motor);const prop=new THREE.Group();prop.position.set(mx,.26,mz);const blade=new THREE.Mesh(new THREE.BoxGeometry(.85,.02,.12),matProp);blade.rotation.z=.12;prop.add(blade);const b2=blade.clone();b2.rotation.y=Math.PI/2;prop.add(b2);prop.userData.spin=(i%2===0)?1:-1;g.add(prop);hotspots.push({name:'Motor M'+(i+1),obj:prop,info:'Motor brushless. Giro '+(i%2===0?'horario':'antihorario')+'.',tag:'Estimado'});g.userData.props=g.userData.props||[];g.userData.props.push(prop);});
if(version==='eco'){const cam=new THREE.Mesh(new THREE.BoxGeometry(.22,.18,.2),matDark);cam.position.set(.82,-.05,0);g.add(cam);const lens=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,.05,16),matAcc);lens.rotation.z=Math.PI/2;lens.position.set(.95,-.05,0);g.add(lens);hotspots.push({name:'Cámara frontal',obj:cam,info:'Cámara fija. Análisis en tierra.',tag:'Estimado'});const gps=new THREE.Mesh(new THREE.BoxGeometry(.22,.06,.22),matAcc);gps.position.set(-.3,.3,0);g.add(gps);hotspots.push({name:'GPS',obj:gps,info:'Rutas por waypoints.',tag:'Estimado'});const pms=new THREE.Mesh(new THREE.BoxGeometry(.3,.2,.25),matDark);pms.position.set(-.35,-.32,0);g.add(pms);hotspots.push({name:'Sensor de partículas',obj:pms,info:'Mide PM1.0/2.5/10. No detecta microplásticos.',tag:'A validar'});const bat=new THREE.Mesh(new THREE.BoxGeometry(.7,.18,.4),new THREE.MeshStandardMaterial({color:0x333333,roughness:.6}));bat.position.set(0,-.32,0);g.add(bat);hotspots.push({name:'Batería LiPo 3S',obj:bat,info:'Autonomía estimada.',tag:'Estimado'});}
else{const gim=new THREE.Group();gim.position.set(.8,-.28,0);const gb=new THREE.Mesh(new THREE.BoxGeometry(.3,.25,.3),matDark);gim.add(gb);const rgb=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.08,16),matAcc);rgb.rotation.z=Math.PI/2;rgb.position.set(.2,0,.08);gim.add(rgb);const term=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,.08,16),new THREE.MeshStandardMaterial({color:0x8a2be2,roughness:.3}));term.rotation.z=Math.PI/2;term.position.set(.2,0,-.08);gim.add(term);g.add(gim);hotspots.push({name:'Gimbal + doble cámara',obj:gim,info:'RGB y térmica estabilizada.',tag:'Estimado'});const mast=new THREE.Mesh(new THREE.CylinderGeometry(.02,.02,.5),matArm);mast.position.set(-.4,.5,0);g.add(mast);const rtk=new THREE.Mesh(new THREE.SphereGeometry(.09,12,12),matAcc);rtk.position.set(-.4,.78,0);g.add(rtk);hotspots.push({name:'Antena RTK',obj:rtk,info:'GPS de alta precisión.',tag:'Estimado'});const tel=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,.4),matArm);tel.position.set(.35,.45,.3);tel.rotation.x=.3;g.add(tel);hotspots.push({name:'Telemetría / 4G',obj:tel,info:'Datos y alertas en tiempo real.',tag:'A validar'});const mk=(c,x,z)=>{const l=new THREE.Mesh(new THREE.SphereGeometry(.05,10,10),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1}));l.position.set(x,.1,z);g.add(l);return l;};const nav=[mk(0xff3333,-.7,.7),mk(0x33ff66,.7,.7),mk(0xffffff,0,-.75)];g.userData.nav=nav;hotspots.push({name:'Luces de navegación',obj:nav[0],info:'Roja izq, verde der, blanca trasera.',tag:'Estimado'});const bat=new THREE.Mesh(new THREE.BoxGeometry(.8,.2,.45),matDark);bat.position.set(0,-.35,0);g.add(bat);hotspots.push({name:'Batería',obj:bat,info:'Mayor capacidad.',tag:'Estimado'});}
const fc=new THREE.Mesh(new THREE.BoxGeometry(.5,.06,.5),matDark);fc.position.set(0,.02,0);g.add(fc);hotspots.push({name:'Controladora',obj:fc,info:version==='eco'?'ArduPilot/Betaflight + GPS. ESP32 = misión.':'Pixhawk 6C / Cube Orange.',tag:'Estimado'});
g.userData.hotspots=hotspots;return{group:g,hotspots};};
